### ISSUE TITLE
Minimum PHP version 5.5

### ISSUE THREAD

**Issue by chadicus** [hrphp/hrphp-framework#13]
PHP 5.4's end of life is September of this year.  See [this link](http://php.net/supported-versions.php)

Should we go ahead and up the min supported version of php to 5.5?

**Comment by guillermoandrae** [comment]
I like the idea of supporting at least 2 minor versions back from the latest stable. [zf2](https://github.com/zendframework/zf2/blob/master/composer.json#L12) and [symfony](https://github.com/symfony/symfony/blob/2.7/composer.json#L19) both support some versions of 5.3 -- I wouldn't like to go back that far. 5.4 is good enough IMO.

**Comment by guillermoandrae** [comment]
@chadicus got any other thoughts on this?

**Comment by chadicus** [comment]
I will say ZF3 is scheduled to be released later this year and it's min version will be 5.5.

**Comment by guillermoandrae** [comment]
OK. If newer frameworks are doing it, then we should, too. Create a PR and I'll get it merged.
