### ISSUE TITLE
Use PSR-7 

### ISSUE THREAD

**Issue by chadicus** [hrphp/hrphp-framework#7]
I think it would be great for the framework to use the proposed psr-7 http-message standards.

**Comment by guillermoandrae** [comment]
Definitely a good idea.

**Comment by guillermoandrae** [comment]
@chadicus or @troy0820 ... I think it would be great if one of you could take this one.

**Comment by chadicus** [comment]
@troy0820 and I could split the work. We need concrete implementations of the interfaces found [here](https://github.com/php-fig/http-message/tree/master/src)

**Comment by chadicus** [comment]
Perhaps all of them are not needed, just the `RequestInterface` and `ResponseInterface` for now

**Comment by guillermoandrae** [comment]
@troy0820 or @chadicus?
